# .github/scripts/write-e2e-env.py
# CI-only: build a disposable .env for the E2E Compose stack from the ephemeral
# ES256 PEM files generated by the workflow. Reading the PEMs as file bytes and
# JSON-quoting them avoids all shell escaping of multiline secrets.
import json
priv = open('/tmp/jwt-priv.pem').read()
pub = open('/tmp/jwt-pub.pem').read()
lines = [
    'POSTGRES_USER=fleet',
    'POSTGRES_PASSWORD=fleet',
    'POSTGRES_DB=fleet',
    'DB_AUTO_MIGRATE=true',
    'JWT_ISSUER=fleet-pilot-api',
    'JWT_AUDIENCE=fleet-driver',
    'JWT_PRIVATE_KEY_PEM=' + json.dumps(priv),
    'JWT_PUBLIC_KEY_PEM=' + json.dumps(pub),
]
open('.env', 'w').write('\n'.join(lines) + '\n')
print('wrote .env lines:', len(lines))
