-- apps/api/src/database/migrations/0018_amused_firebird.sql
-- EXPAND-only (parallel-change): add nullable customer.phone (VN domestic phone,
-- e.g. 0901234567, no +84). Nullable so existing rows and old code that never
-- sets phone remain valid during the deploy overlap. No NOT NULL, no rewrite,
-- no drop. cargo_type_id / driver_password_reset_log were regenerated by a stale
-- drizzle-kit snapshot but already exist in the DB (prior migrations) — excluded.
ALTER TABLE "customer" ADD COLUMN "phone" varchar(32);
